### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by liamxg** [clifmckee/phylogeo-bats-bartonella#1]
could you please send me the data, please, thanks.

**Comment by clifmckee** [comment]
Hi Liam! Can I ask which data you are looking for? The sequences and metadata were stored across multiple files, so it would be helpful to have more details on what you need before I go searching in my archives.

**Comment by liamxg** [comment]
I want to run your code, and many data in the r code can not find, thanks.
for example: mammterr=readShapeSpatial("C:/Users/newUser/Documents/Thesis/Infection, Genetics, and Evolution draft/TERRESTRIAL_MAMMALS/TERRESTRIAL_MAMMALS.shp")

**Comment by clifmckee** [comment]
Unfortunately, the shapefile is too large for me to put on Github. That data came from IUCN and can be found [here](https://www.iucnredlist.org/resources/spatial-data-download) - the "Terrestrial Mammals" dataset.

As for the remaining data for the cophylogenetic analysis code, that has all been added and the code has been updated to use functions from the R "paco" package that came out after I finished the original analysis.

I also put up some other code that plots IUCN range maps in another repository [here](https://github.com/clifmckee/IUCN_range_overlap) in case it is helpful.

**Comment by liamxg** [comment]
thanks, i will try to find out it.

**Comment by liamxg** [comment]
that's great, can we cooperate with each other.

**Comment by clifmckee** [comment]
Sorry for the long delay. How would you like to work together? You can email me at clifton.mckee@gmail.com if you have ideas for a project.
